[package]
name = "ocsf-semantic"
description = "Semantic model definitions and validation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true
ocsf-core.workspace = true

[dev-dependencies]
proptest.workspace = true
